name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        zig-version: [master]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - zig-version: "0.12.1"
            os: ubuntu-latest
          - zig-version: "0.13.0"
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: ${{ matrix.zig-version }}

      - name: Install Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libgtk-3-dev libdbus-1-dev

      - name: Check Formatting
        run: zig fmt --ast-check --check .

      - name: Build
        run: zig build install install-tests --summary all

      - name: Build with -Dportal
        if: matrix.os == 'ubuntu-latest'
        run: zig build install install-tests -Dportal --summary all
